### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by vishalanandl177** [suyashphatak23/Snapdeal-Mobile-Pricing-Scraper#1]
**HTTP Error 403: Forbidden**

If you deploy this on AWS EC2 or Digital Ocen Droplet, It is giving error. HTTP Error 403: Forbidden

**Comment by suyashphatak23** [comment]
I think it is because Snapdeal is not granting the permission to access the website. 
Try changing the URL to different URL.

**Comment by vishalanandl177** [comment]
I have already tried using different URLs. Only for Snapdeal, it is not working, Amazon and Flipkart working.

**Comment by suyashphatak23** [comment]
# I have changed the code.
Please try again and let me know.

**Comment by vishalanandl177** [comment]
Same issue.  HTTP Error 403: Forbidden.

`Traceback (most recent call last):
  File "test.py", line 34, in <module>
    content = urllib.request.urlopen(req).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

**Comment by suyashphatak23** [comment]
It works fine in my computer. Can you please try on another device.

**Comment by vishalanandl177** [comment]
Locally, it is working but never worked over the server.
This "HTTP Error 403: Forbidden" I'm getting over the server.

Try deploying the code to AWS EC2 or Digital Ocean and run the code there.
